### ISSUE TITLE
Fails to compile in kernel 5.13

### ISSUE THREAD

**Issue by bsense-rius** [dimich-dmb/spi-ch341-usb#2]
Unfortunately fails to compile in 5.13 :(

Says: Skipping BTF generation xxx. due to unavailability of vmlinux in ubuntu 20.04 kernel 5.13

Keep with the good work! Would appreciate to have same fixes for the i2c_driver as well.

Thank you very much however!

**Comment by UncleGrumpy** [comment]
That is kind of a strange sounding error... can you post the compiler output starting a few lines before the error?

**Comment by dimich-dmb** [comment]
> Unfortunately fails to compile in 5.13 :(

Sorry, looks like it's ubuntu-specific issue, not related to particular driver. I compiled the driver for 5.13 in Arch linux without any error.

> Would appreciate to have same fixes for the i2c_driver as well.

For I2C i use [this](https://github.com/gmarco/i2c-ch341) driver, it works fine on recent kernels too.
